language: ruby
rvm:
- 2.3.3

install:
    - python -m pip install --user pyyaml
    - bundle install --jobs=3 --retry=3

script:
    - bundle exec jekyll build --config _config.yml
    - bundle exec htmlproofer ./_site
    - make unittest
    - make lesson-check-all

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# Use travis-ci's container-based infrastructure for a faster build
sudo: false