language: python
python: 3.6
branches:
  only:
  - gh-pages
  - /.*/
before_install:
  - rvm default
  - gem install json kramdown jekyll
  - apt-get install r-base
  - Rscript -e "install.packages('knitr', dependencies = TRUE)"
  - Rscript -e "install.packages('stringr', dependencies = TRUE)"
  - Rscript -e "install.packages('checkpoint', dependencies = TRUE)"
install:
  - pip install pyyaml
script:
  - make lesson-check-all
  - make --always-make site
